name: Ruff Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ruff:
    uses: A-TownChain-Okosystems/.github/.github/workflows/reusable-ruff.yml@32fe26adf17261513a8c341011967a69c08b0bf7
    permissions:
      contents: read
